version: 0.2

phases:
  install:
    commands:
      - echo Entering Install Phase..
      - npm install
  pre_build:
    commands:
      - echo Entering pre_build Phase...
  build:
    commands:
      - echo Entering build Phase...
      - echo Build started on `date`
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
#reports:
#  group2-ted: #surefire junit reports   
#    files:
#      - '**/*'
#   base-directory: 'target/surefire-reports/'
#reports:
#  group2-ted:
#    files:
#      - "target/surefire-reports/*.json"
#    file-format: "CUCUMBERJSON"
artifacts:
  files:
  - '**/*'